# Zika - Import

## Setup

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display, Markdown
pd.set_option('display.max_columns', None)
sns.set_style('darkgrid')

SEED = 2026

## Dataset

In [5]:
df_zika = pd.read_csv("orig/train.csv")
display(Markdown("## `df_zika`"))
display(df_zika.shape)
display(df_zika.head(1))

## `df_zika`

(2138, 19)

,location,EW,EW_start_date,pop,cases,cases_est,cases_est_min,cases_est_max,p_rt1,p_inc100k,Sublocation,alert,id,model_version,tweet,Rt,receptivity,transmission,epidemic_threshold
0,A,201501,2015-01-04,12325232,0,0.0,0,0,0.5,0.0,0,1,355030820150119589,2023-08-20,0,0.0,0,0,0

In [ ]:
df_score = pd.read_csv("orig/test.csv")
display(Markdown("## `df_score`"))
display(df_score.shape)
display(df_score.head(1))

## `df_score`

(2138, 19)

,location,EW,EW_start_date,pop,cases,cases_est,cases_est_min,cases_est_max,p_rt1,p_inc100k,Sublocation,alert,id,model_version,tweet,Rt,receptivity,transmission,epidemic_threshold
0,A,201501,2015-01-04,12325232,0,0.0,0,0,0.5,0.0,0,1,355030820150119589,2023-08-20,0,0.0,0,0,0

In [8]:
df_dengue = pd.read_csv("orig/dengue.csv")
display(Markdown("## `df_dengue`"))
display(df_dengue.shape)
display(df_dengue.head(1))

## `df_dengue`

(3444, 10)

,location,EW,EW_start_date,cases,p_rt1,p_inc100k,alert,Rt,transmission,epidemic_threshold
0,A,201501,2015-01-04,370,1.0,3.001972,2,3.434149,1,1

In [9]:
df_weather = pd.read_csv("orig/weather.csv")
display(Markdown("## `df_weather`"))
display(df_weather.shape)
display(df_weather.head(1))

## `df_weather`

(19018, 28)

,location,date,temperature_2m_min,temperature_2m_max,temperature_2m_mean,apparent_temperature_min,apparent_temperature_max,apparent_temperature_mean,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant,precipitation_sum,precipitation_hours,rain_sum,showers_sum,precipitation_probability_min,precipitation_probability_max,precipitation_probability_mean,sunshine_duration,daylight_duration,shortwave_radiation_sum,cloud_cover_mean,dew_point_2m_min,dew_point_2m_max,dew_point_2m_mean,relative_humidity_2m_mean,soil_moisture_0_to_7cm_mean,et0_fao_evapotranspiration
0,A,2015-01-04,21.036999,25.387,22.459915,23.57125,29.486015,25.565351,14.587776,28.44,137.45909,20.9,12.0,20.9,0.0,NaN,NaN,NaN,28601.842,48720.734,16.83,95.375,20.137,21.237,20.557833,89.229454,0.482583,3.162444

In [10]:
df_sample_submission = pd.read_csv("orig/sample_submission.csv")
display(Markdown("## `df_sample_submission`"))
display(df_sample_submission.shape)
display(df_sample_submission.head(1))

## `df_sample_submission`

(572, 2)

        ID  cases
0  A202201      1

## EDA

### Cleaning

In [12]:
df_zika.dtypes

location               object
EW                      int64
EW_start_date          object
pop                     int64
cases                   int64
cases_est             float64
cases_est_min           int64
cases_est_max           int64
p_rt1                 float64
p_inc100k             float64
Sublocation             int64
alert                   int64
id                      int64
model_version          object
tweet                   int64
Rt                    float64
receptivity             int64
transmission            int64
epidemic_threshold      int64
dtype: object

In [13]:
for df in [df_zika, df_score, df_dengue]:
    df['EW_start_date'] = pd.to_datetime(df['EW_start_date'])

df_weather['date'] = pd.to_datetime(df_weather['date'])

In [14]:
df_zika.location.value_counts()

location
A    365
C    365
D    365
E    365
F    365
B    313
Name: count, dtype: int64

In [17]:
df_zika.groupby("EW_start_date").location.count().value_counts()

location
6    313
5     52
Name: count, dtype: int64

In [ ]:
locations = df_zika.location.unique()
fig, axs = plt.subplots(len(locations), 1, figsize=(15, 5), sharex=True)

for location, ax in zip(locations, axs):
    criteria = "location == @location"
    sns.lineplot(data=df_zika.query(criteria), x="EW_start_date", y="total_cases", ax=ax, title=location)